name: Release

on:
  push:
    branches:
      - main
      - beta
  workflow_dispatch:

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: 🙌 Prepare release
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          token: ${{ secrets.ACCESS_TOKEN }}
          extra-files: |
            database.dbml
            prepend.py
            shift.py
            README.md
          pull-request-title-pattern: "chore${scope}: release${component} v${version}"
          package-name: "open-discogs-erd"
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
